version: '3'

services:
    web:
        image: webdevops/php:8.3
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            - "TZ=Europe/Budapest"
        ports:
            - 9000:80
